[package]
name = "akari-ffi"
description = "UniFFI bindings for Akari (Swift and Kotlin)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
akari-core.workspace = true
akari-markdown.workspace = true

[lints]
workspace = true
